apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-arbeidssokerregister-adapter
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 3
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{ kafka.pool }}
  env:
    - name: ARBEIDSSOKERREGISTER_HOST
      value: {{ ARBEIDSSOKERREGISTER_HOST }}
    - name: ARBEIDSSOKERREGISTER_SCOPE
      value: {{ ARBEIDSSOKERREGISTER_SCOPE }}
    - name: ARBEIDSSOKERPERIODER_TOPIC
      value: {{ ARBEIDSSOKERPERIODER_TOPIC }}
    - name: OVERTA_BEKREFTELSE_TOPIC
      value: {{ OVERTA_BEKREFTELSE_TOPIC }}
    - name: BEKREFTELSE_TOPIC
      value: {{ BEKREFTELSE_TOPIC }}
