apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-arbeidssokerregister-adapter
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 3
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  kafka:
    pool: {{ kafka.pool }}
  accessPolicy:
    outbound:
      rules:
        - application: paw-arbeidssoekerregisteret-api-oppslag
          namespace: paw
          cluster: dev-gcp
        - application: paw-kafka-key-generator
          namespace: paw
          cluster: dev-gcp
  env:
    - name: ARBEIDSSOKERREGISTER_OPPSLAG_HOST
      value: {{ ARBEIDSSOKERREGISTER_OPPSLAG_HOST }}
    - name: ARBEIDSSOKERREGISTER_OPPSLAG_SCOPE
      value: {{ ARBEIDSSOKERREGISTER_OPPSLAG_SCOPE }}
    - name: ARBEIDSSOKERREGISTER_RECORD_KEY_HOST
      value: {{ ARBEIDSSOKERREGISTER_RECORD_KEY_HOST }}
    - name: ARBEIDSSOKERPERIODER_TOPIC
      value: {{ ARBEIDSSOKERPERIODER_TOPIC }}
    - name: OVERTA_BEKREFTELSE_TOPIC
      value: {{ OVERTA_BEKREFTELSE_TOPIC }}
    - name: BEKREFTELSE_TOPIC
      value: {{ BEKREFTELSE_TOPIC }}
